# Generated by Django 2.0 on 2019-03-23 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.IntegerField()),
                ('How', models.CharField(default='some string', max_length=100)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 18, 6, 58, 945944))),
                ('Comments', models.CharField(default='some string', max_length=100)),
                ('Customer_number', models.IntegerField()),
                ('Staff_user_id', models.IntegerField()),
                ('Staff_name', models.CharField(default='some string', max_length=100)),
                ('Satisfied', models.BooleanField()),
                ('Bank_id', models.CharField(default='some string', max_length=100)),
            ],
        ),
    ]
