# Generated by Django 2.0 on 2019-03-23 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 18, 8, 5, 500455)),
        ),
    ]
