# Generated by Django 2.0 on 2019-03-23 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20190323_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 23, 18, 9, 27, 600661)),
        ),
    ]
